spring:
  datasource:
    username:
    password:
    url: jdbc:postgresql://192.168.0.100:5432/spring-data-jpa
  jpa:
    hibernate:
      # This property will drop everything once the application shuts down
      # Is only set for dev/testing env
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
